/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_coolreader_newui_CRView */

#ifndef _Included_org_coolreader_newui_CRView
#define _Included_org_coolreader_newui_CRView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_coolreader_newui_CRView
 * Method:    initInternal
 * Signature: (Lorg/coolreader/newui/CRConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_coolreader_newui_CRView_initInternal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    isLink
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_coolreader_newui_CRView_isLink
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    callCRRunnableInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_coolreader_newui_CRView_callCRRunnableInternal
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
