/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_coolreader_newui_CRView */

#ifndef _Included_org_coolreader_newui_CRView
#define _Included_org_coolreader_newui_CRView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_coolreader_newui_CRView
 * Method:    initInternal
 * Signature: (Lorg/coolreader/newui/CRConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_coolreader_newui_CRView_initInternal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    uninitInternal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_coolreader_newui_CRView_uninitInternal
  (JNIEnv *, jobject);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    drawInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_coolreader_newui_CRView_drawInternal
  (JNIEnv *, jobject);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    surfaceChangedInternal
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_coolreader_newui_CRView_surfaceChangedInternal
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    surfaceDestroyedInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_coolreader_newui_CRView_surfaceDestroyedInternal
  (JNIEnv *, jobject);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    handleKeyEventInternal
 * Signature: (Landroid/view/KeyEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_coolreader_newui_CRView_handleKeyEventInternal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    handleTouchEventInternal
 * Signature: (Landroid/view/MotionEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_coolreader_newui_CRView_handleTouchEventInternal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    isLink
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_coolreader_newui_CRView_isLink
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    loadBookInternal
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_coolreader_newui_CRView_loadBookInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    setBatteryLevelInternal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_coolreader_newui_CRView_setBatteryLevelInternal
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_coolreader_newui_CRView
 * Method:    callCRRunnableInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_coolreader_newui_CRView_callCRRunnableInternal
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
